<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "annuaire_famo"
 *
 * Auto generated by Extension Builder 2017-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Annuaire - Famo',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Thibault FAIVRE, Michael MONDOU',
	'author_email' => 'thibault.faivre@etu.u-bordeaux.fr, michael.mondou@etu.u-bordeaux.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);